add_newline = false
[character]
format = "$symbol"
success_symbol = "[âœ ](bold green)"
error_symbol = "[âœ ](bold red)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) in "
disabled = false
show_always = true

[directory]
truncation_length = 8
format = "[$path]($style) [$read_only]($read_only_style) "
read_only = " ï ½"
truncation_symbol = "â€¦/"

[nodejs]
format = "via [$symbol ($version)]($style) "
symbol = "î‰ "

[dart]
format = "via [$symbol ($version)]($style) "
symbol = "ğŸ¯"
detect_extensions = ['dart']
style = "bold blue"
detect_files = ["pubspec.yaml", "pubspec.yml", "pubspec.lock"]

[package]
symbol = "ï£– "

[python]
symbol = "î˜† "

[git_branch]
symbol = "ï˜ "

[cmd_duration]
format = "took [$duration](bold yellow) "
show_milliseconds = false
