# Inserts a blank line between shell prompts
add_newline = true

[hostname]
ssh_only = false
format =  "[$hostname]($style) in "
trim_at = ".companyname.com"
disabled = false
style = "bold dimmed green"

[directory]
truncation_length = 8
format = "[$path]($style) [$read_only]($read_only_style) "
read_only = "ğŸ”’"
truncation_symbol = "â€¦/"

[nodejs]
format = "via [$symbol ($version )]($style)"
symbol = "ğŸ¤–"

[dart]
format = "via [$symbol ($version )]($style)"
symbol = "ğŸ¯"
detect_extensions = ['dart']
style = "bold blue"
detect_files = ["pubspec.yaml", "pubspec.yml", "pubspec.lock"]

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
format = "$symbol"
success_symbol = "[âœ ](bold green)"
error_symbol = "[âœ ](bold red)"